name: countries
description: Submission for Trademarkia assessment

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.3.5
  cupertino_icons: ^1.0.2
  http:
  http_parser:
  sqflite: ^2.0.0+4
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icons8-america-100.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icons8-america-100.png

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Bold.otf
        - asset: assets/fonts/Proxima-Nova-Regular.ttf
          weight: 800
